.TH BAMSPLIT 1 "October 2013" BIOBAMBAM
.SH NAME
bamsplit - split BAM files
.SH SYNOPSIS
.PP
.B bamsplit
[options]
.SH DESCRIPTION
bamsplit reads a BAM file via standard input and creates a set of output
files with at most a given number of alignments each. The concatenation of
the output files via bamcat restores the sequence of alignments in the
original input file. The splitting does not consider read pairs, i.e. the
ends of pairs can end up in separate files.
.PP
The following key=value pairs can be given:
.PP
.B n=<65536>:
number of alignments per output file.
.PP
.B prefix=<filename>
prefix for the create files. The created files will have names ${prefix}_000000.bam, ${prefix}_000001.bam, etc.
.PP
.B level=<-1|0|1|9|11>:
set compression level of the output BAM file. Valid
values are
.IP -1:
zlib/gzip default compression level
.IP 0:
uncompressed
.IP 1:
zlib/gzip level 1 (fast) compression
.IP 9:
zlib/gzip level 9 (best) compression
.P
If libmaus has been compiled with support for igzip (see
https://software.intel.com/en-us/articles/igzip-a-high-performance-deflate-compressor-with-optimizations-for-genomic-data)
then an additional valid value is
.IP 11:
igzip compression
.PP
.B verbose=<1>:
Valid values are
.IP 1:
print progress report on standard error
.IP 0:
do not print progress report
.SH AUTHOR
Written by German Tischler.
.SH "REPORTING BUGS"
Report bugs to <gt1@sanger.ac.uk>
.SH COPYRIGHT
Copyright \(co 2009-2013 German Tischler, \(co 2011-2013 Genome Research Limited.
License GPLv3+: GNU GPL version 3 <http://gnu.org/licenses/gpl.html>
.br
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
